shared/Logger.m:93 - /Users/Kate/Library/Application Support/Google/Drive/GoogleDriveIpcPipe is a symbolic link to /Users/Kate/Library/Group Containers/google_drive/tmpZjze3n, connecting to link target.
2020-05-09 17:47:12 /var/netboot/tmp/tmpfs/src/piper/googleclient/apps/webdrive_sync/osx/ext/shared/Logger.m:93 - Pipe path is a symbolic link, connecting to target.
2020-05-09 17:47:12 /var/netboot/tmp/tmpfs/src/piper/googleclient/apps/webdrive_sync/osx/ext/shared/Logger.m:93 - /Users/Kate/Library/Application Support/Google/Drive/GoogleDriveIpcPipe is a symbolic link to /Users/Kate/Library/Group Containers/google_drive/tmpZjze3n, connecting to link target.
2020-05-09 17:47:14 /var/netboot/tmp/tmpfs/src/piper/googleclient/apps/webdrive_sync/osx/ext/shared/Logger.m:93 - Pipe path is a symbolic link, connecting to target.
2020-05-09 17:47:14 /var/netboot/tmp/tmpfs/src/piper/googleclient/apps/webdrive_sync/osx/ext/shared/Logger.m:93 - /Users/Kate/Library/Application Support/Google/Drive/GoogleDriveIpcPipe is a symbolic link to /Users/Kate/Library/Group Containers/google_drive/tmpZjze3n, connecting to link target.
2020-05-09 17:47:15 /var/netboot/tmp/tmpfs/src/piper/googleclient/apps/webdrive_sync/osx/ext/shared/Logger.m:93 - Pipe path is a symbolic link, connecting to target.
2020-05-09 17:47:15 /var/netboot/tmp/tmpfs/src/piper/googleclient/apps/webdrive_sync/osx/ext/shared/Logger.m:93 - /Users/Kate/Library/Application Support/Google/Drive/GoogleDriveIpcPipe is a symbolic link to /Users/Kate/Library/Group Containers/google_drive/tmpJvDkxT, connecting to link target.
2020-05-09 17:47:16 /var/netboot/tmp/tmpfs/src/piper/googleclient/apps/webdrive_sync/osx/ext/shared/Logger.m:93 - Pipe path is a symbolic link, connecting to target.
2020-05-09 17:47:16 /var/netboot/tmp/tmpfs/src/piper/googleclient/apps/webdrive_sync/osx/ext/shared/Logger.m:93 - /Users/Kate/Library/Application Support/Google/Drive/GoogleDriveIpcPipe is a symbolic link to /Users/Kate/Library/Group Containers/google_drive/tmpbSoZ3U, connecting to link target.
2020-05-09 17:47:18 /var/netboot/tmp/tmpfs/src/piper/googleclient/apps/webdrive_sync/osx/ext/shared/Logger.m:93 - Pipe path is a symbolic link, connecting to target.
2020-05-09 17:47:18 /var/netboot/tmp/tmpfs/src/piper/googleclient/apps/webdrive_sync/osx/ext/shared/Logger.m:93 - /Users/Kate/Library/Application Support/Google/Drive/GoogleDriveIpcPipe is a symbolic link to /Users/Kate/Library/Group Containers/google_drive/tmpbSoZ3U, connecting to link target.
2020-05-09 17:47:21 /var/netboot/tmp/tmpfs/src/piper/googleclient/apps/webdrive_sync/osx/ext/shared/Logger.m:93 - Pipe path is a symbolic link, connecting to target.
2020-05-09 17:47:21 /var/netboot/tmp/tmpfs/src/piper/googleclient/apps/webdrive_sync/osx/ext/shared/Logger.m:93 - /Users/Kate/Library/Application Support/Google/Drive/GoogleDriveIpcPipe is a symbolic link to /Users/Kate/Library/Group Containers/google_drive/tmpL6Zeaf, connecting to link target.
2020-05-09 17:47:24 /var/netboot/tmp/tmpfs/src/piper/googleclient/apps/webdrive_sync/osx/ext/shared/Logger.m:93 - Pipe path is a symbolic link, connecting to target.
2020-05-09 17:47:24 /var/netboot/tmp/tmpfs/src/piper/googleclient/apps/webdrive_sync/osx/ext/shared/Logger.m:93 - /Users/Kate/Library/Application Support/Google/Drive/GoogleDriveIpcPipe is a symbolic link to /Users/Kate/Library/Group Containers/google_drive/tmpL6Zeaf, connecting to link target.
2020-05-09 17:47:26 /var/netboot/tmp/tmpfs/src/piper/googleclient/apps/webdrive_sync/osx/ext/shared/Logger.m:93 - Pipe path is a symbolic link, connecting to target.
2020-05-09 17:47:26 /var/netboot/tmp/tmpfs/src/piper/googleclient/apps/webdrive_sync/osx/ext/shared/Logger.m:93 - /Users/Kate/Library/Application Support/Google/Drive/GoogleDriveIpcPipe is a symbolic link to /Users/Kate/Library/Group Containers/google_drive/tmp4Rhd3S, connecting to link target.
2020-05-09 17:47:39 /var/netboot/tmp/tmpfs/src/piper/googleclient/apps/webdrive_sync/osx/ext/shared/Logger.m:93 - Pipe path is a symbolic link, connec